[package]
name = "beacn-utility"
version = "0.2.5"
edition = "2024"
authors = ["Craig McLure <craig@mclure.net>"]
description = "Allows Configuration of Beacn Devices"
repository = "https://github.com/beacn-on-linux/beacn-utility"
license = "MIT"
categories = ["hardware-support"]
build = "build.rs"


[dependencies]
# Logging
log = "0.4.33"
simplelog = "0.12.2"
file-rotate = "0.8.0"
log-panics = { version = "2.1.0", features = ["with-backtrace"] }

# Error Handling
anyhow = "1.0.104"

# Async Runtime
tokio = { version = "1.53.1", features = ["rt-multi-thread", "signal"] }

# Opening Stuff
open = "5.4.0"

# Enum Helpers
strum = "0.28.0"
strum_macros = "0.28.0"
enum-map = "2.7.3"

# Used for Sending and Receiving Messages
oneshot = "0.2.1"

# Used for SIMD EQ calculations
wide = "1.5.0"

# UI Framework (iced)
iced = { version = "0.14.0", features = ["tokio", "advanced", "svg", "canvas"] }
iced_futures = "0.14.0"
iced_color_picker = "0.14.0"

unicode-segmentation = "1"
emath = "0.36.1"


# Grab beacn-mic-lib for comms
#beacn-lib = { git = "https://github.com/beacn-on-linux/beacn-lib.git", branch = "main", features = ["tokio"] }
beacn-lib = { git = "https://github.com/beacn-on-linux/beacn-lib.git", tag = "v0.2.3", features = ["tokio"] }
#beacn-lib = { path = "../beacn-lib", features = ["tokio"] }

# Image Handling
image = "0.25.10"
fontdue = "0.9.3"

# For Creating .desktop files outside the flatpak runtime
rust-ini = "0.21.3"

# Profile Loading / Saving
serde = "1.0.229"
serde_json = "1.0.151"

# Pipeweaver Stuff
interprocess = { version = "2.4.2", features = ["tokio"] }
tokio-tungstenite = "0.30.0"
futures-lite = "2.6.1"
json-patch = "4.2.0"

directories = "6.0.0"
rayon = "1.12.0"



# Used for Spectrum Analysis
rustfft = "6.4.1"
num-complex = "0.4.6"

[target.'cfg(unix)'.dependencies]
# Apature Science Handheld Portal Device (autostart / background)
ashpd = { version = "0.13.13", features = ["tokio", "raw_handle", "background"] }

# Tray Handler
ksni = { version = "0.3.6", features = ["blocking"] }

# Sleep Management
zbus = { version = "5.18.0", features = ["tokio"] }

# Packaging
[package.metadata.deb]
name = "beacn-utility"
assets = [
    ["target/release/beacn-utility", "usr/bin/", "755"],
    ["50-beacn.rules", "etc/udev/rules.d/", "644"],
    ["resources/icons/beacn-utility.png", "usr/share/icons/hicolor/48x48/apps/", "644"],
    ["resources/icons/beacn-utility-large.png", "usr/share/pixmaps/beacn-utility.png", "644"],
    ["resources/icons/beacn-utility.svg", "usr/share/icons/hicolor/scalable/apps/", "644"],
    ["resources/desktop/io.github.beacn_on_linux.beacn-utility.desktop", "usr/share/applications/", "644"],
]
maintainer-scripts = ".github/ci/DEBIAN/"
section = "sound"
priority = "optional"
depends = "$auto"
extended-description = """\
A utility for monitoring and controlling Beacn Devices
"""
revision = "1"

## cargo generate-rpm support..
[package.metadata.generate-rpm]
name = "beacn-utility"

assets = [
    { source = "target/release/beacn-utility", dest = "/usr/bin/beacn-utility", mode = "0755" },
    { source = "50-beacn.rules", dest = "/etc/udev/rules.d/50-beacn.rules", mode = "0644" },
    { source = "resources/icons/beacn-utility.png", dest = "/usr/share/icons/hicolor/48x48/apps/beacn-utility.png", mode = "0644" },
    { source = "resources/icons/beacn-utility-large.png", dest = "/usr/share/pixmaps/beacn-utility.png", mode = "0644" },
    { source = "resources/icons/beacn-utility.svg", dest = "/usr/share/icons/hicolor/scalable/apps/beacn-utility.svg", mode = "0644" },
    { source = "resources/desktop/io.github.beacn_on_linux.beacn-utility.desktop", dest = "/usr/share/applications/io.github.beacn_on_linux.beacn-utility.desktop", mode = "0644" },
]

# Tiny scriptlet, should reload udev if possible.
post_install_script = """
udevadm control --reload-rules || echo -e "\\033[0;31mReloading udev failed. You might need to reboot after installation.\\033[0m" 1>&2
udevadm trigger || echo -e "\\033[0;31mReloading udev failed. You might need to reboot after installation.\\033[0m" 1>&2
"""

#release = "1"

# Because we build under Ubuntu in CI, generate-rpm is unable to calculate the dependencies required (no access
# to rpm / yum), so we need to disable the auto and specify dependencies manually.
auto-req = "no"
